# -*- coding: utf-8 -*-
"""Potentia Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WljpcFqlquG8mU-NnKZzf4yTvXIrVsIC
"""

import requests
import json
import pandas as pd

df = pd.read_csv('/content/Movies_title1.csv')
dataz = df['Title'].tolist()
finalcsv = pd.DataFrame()

for i in range(99):
  url = 'http://www.omdbapi.com/?apikey=d1c6c9e8&t='+dataz[i]
  response = requests.get(url)

  if response.status_code== 200:
    data = response.json()
    d = pd.DataFrame(data)
    finalcsv = finalcsv.append(d, ignore_index = True)
  else:
    print("Error: ", response.status_code)
finalcsv = finalcsv.apply(lambda x: x.astype(str).str.title()).drop_duplicates(subset=['Title'], keep='first')
finalcsv.to_csv('/content/MovieAPI.csv')

lid = {}
index = 1
lang1 = finalcsv['Language'].str.split(', ', expand=True).stack().reset_index(drop=True)
li = lang1.tolist()
li = set(li)
for i in li:
    lid[i] = index
    index = index + 1

language_dim = []
for l in li:
    language_dim.append({"LID" : lid[l], "Lname" : l})
language_dim = pd.DataFrame(language_dim)
language_dim.to_csv("Language Dimension.csv", index=False)

language_brid = []
for i, row in finalcsv.iterrows():
  mid = row['imdbID']
  lang1 = str(row['Language']).split(', ')
  for l in lang1:
    language_brid.append({"movID": mid, "LID" : lid[l]})
language_brid = pd.DataFrame(language_brid)
language_brid.to_csv("Language Bridge.csv", index=False)

did = {}
indexdir = 1
dir1 = finalcsv['Director'].str.split(', ', expand=True).stack().reset_index(drop=True)
di = dir1.tolist()
di = set(di)
for i in di:
    did[i] = indexdir
    indexdir = indexdir + 1

director_dim = []
for l in di:
    director_dim.append({"DID" : did[l], "Dname" : l})
director_dim = pd.DataFrame(director_dim)
director_dim.to_csv("Director Dimension.csv", index=False)

director_brid = []
for i, row in finalcsv.iterrows():
  mid = row['imdbID']
  dire1 = str(row['Director']).split(', ')
  for l in dire1:
    director_brid.append({"movID": mid, "DID" : did[l]})
director_brid = pd.DataFrame(director_brid)
director_brid.to_csv("Director Bridge.csv", index=False)

aid = {}
indexactor = 1
actr1 = finalcsv['Actors'].str.split(', ', expand=True).stack().reset_index(drop=True)
ai = actr1.tolist()
ai = set(ai)
for i in ai:
    aid[i] = indexactor
    indexactor = indexactor + 1

actor_dim = []
for l in ai:
    actor_dim.append({"AID" : aid[l], "Aname" : l})
actor_dim = pd.DataFrame(actor_dim)
actor_dim.to_csv("Actor Dimension.csv", index=False)

actor_brid = []
for i, row in finalcsv.iterrows():
  mid = row['imdbID']
  actr1 = str(row['Actors']).split(', ')
  for l in actr1:
    actor_brid.append({"movID": mid, "AID" : aid[l]})
actor_brid = pd.DataFrame(actor_brid)
actor_brid.to_csv("Actor Bridge.csv", index=False)

wid = {}
indexwrit = 1
writ1 = finalcsv['Writer'].str.split(', ', expand=True).stack().reset_index(drop=True)
writ = writ1.tolist()
writ = set(writ)
for i in writ:
    wid[i] = indexwrit
    indexwrit = indexwrit + 1

writer_dim = []
for l in writ:
    writer_dim.append({"WID" : wid[l], "Wname" : l})
writer_dim = pd.DataFrame(writer_dim)
writer_dim.to_csv("Writer Dimension.csv", index=False)

writer_brid = []
for i, row in finalcsv.iterrows():
  mid = row['imdbID']
  writr1 = str(row['Writer']).split(', ')
  for l in writr1:
    writer_brid.append({"movID": mid, "WID" : wid[l]})
writer_brid = pd.DataFrame(writer_brid)
writer_brid.to_csv("Writer Bridge.csv", index=False)

cid = {}
indexcou = 1
coun1 = finalcsv['Country'].str.split(', ', expand=True).stack().reset_index(drop=True)
ci = coun1.tolist()
ci = set(ci)
for i in ci:
    cid[i] = indexcou
    indexcou = indexcou + 1

country_dim = []
for l in ci:
    country_dim.append({"CID" : cid[l], "Cname" : l})
country_dim = pd.DataFrame(country_dim)
country_dim.to_csv("Country Dimension.csv", index=False)

country_brid = []
for i, row in finalcsv.iterrows():
  mid = row['imdbID']
  writr1 = str(row['Country']).split(', ')
  for l in writr1:
    country_brid.append({"movID": mid, "CID" : cid[l]})
country_brid = pd.DataFrame(country_brid)
country_brid.to_csv("Country Bridge.csv", index=False)

gid = {}
indexgenre = 1
genre1 = finalcsv['Genre'].str.split(', ', expand=True).stack().reset_index(drop=True)
gi = genre1.tolist()
gi = set(gi)
for i in gi:
    gid[i] = indexgenre
    indexgenre = indexgenre + 1
gid

genre_dim = []
for l in gi:
    genre_dim.append({"GenreID" : gid[l],"GenreName" : l})
genre_dim = pd.DataFrame(genre_dim)
genre_dim.to_csv("Genre Dimension.csv", index=False)

genre_brid = []
for i, row in finalcsv.iterrows():
  mid = row['imdbID']
  genre1 = str(row['Genre']).split(', ')
  for l in genre1:
    genre_brid.append({"movID": mid, "GenreID" : gid[l]})
genre_brid = pd.DataFrame(genre_brid)
genre_brid.to_csv("Genre Bridge.csv", index=False)

finalcsv['Released'] = pd.to_datetime(finalcsv['Released'])
finalcsv['day'] = finalcsv['Released'].dt.day
finalcsv['month'] = finalcsv['Released'].dt.month

import datetime
tid = {}
indextime = 1
time1 = finalcsv['Released']
ti = time1.tolist()
ti = set(ti)
for i in ti:
    tid[i] = indextime
    indextime = indextime + 1

tid

import datetime
time_dim = []
for i, row in finalcsv.iterrows():
  mid = row['imdbID']
  year = row['Year']
  month = row['month']
  day = row['day']
  timestamp = pd.Timestamp(row['Released'])
  time_dim.append({"movID" : mid, "TimeID" : tid[timestamp],"Year" : year, "Month" : month, "Day" : day})
time_dim = pd.DataFrame(time_dim)
time_dim.to_csv("Time Dimension.csv", index=False)

movie_dim = []
for i, row in finalcsv.iterrows():
  mid = row['imdbID']
  title = row['Title']
  plot = row['Plot']
  movie_dim.append({"movID" : mid, "Title" : title, "Plot" : plot})
movie_dim = pd.DataFrame(movie_dim)
movie_dim.to_csv("Movie Dimension.csv", index=False)

rid = {}
indexrated = 1
rtd1 = finalcsv['Rated']
rated = set(rtd1)
for i in rated:
    rid[i] = indexrated
    indexrated = indexrated + 1

rated_dim = []
for i, row in finalcsv.iterrows():
  mid = row['imdbID']
  value = row['Rated']
  rated_dim.append({"movID" : mid, "RatingID": rid[value], "Value" : value})
rated_dim = pd.DataFrame(rated_dim)
rated_dim.to_csv("Rated Dimension.csv", index=False)

movie_fact = []
for i, row in finalcsv.iterrows():
  mid = row['imdbID']
  metascore = row['Metascore']
  runtime = row['Runtime']
  rating = row['imdbRating']
  movie_fact.append({"movID" : mid, "MetaScore": metascore, "Runtime" : runtime, "Rating": rating})
movie_fact = pd.DataFrame(movie_fact)
movie_fact.to_csv("Movie Fact.csv", index=False)